version: '2'

services:
  bokeh:
    restart: always
    build:
      context: .
    image: structure-property-visualizer:master
    environment:
      BOKEH_PREFIX: ""
      # EXPLORE_URL: "https://dev-www.materialscloud.org/explore/pyrene-mofs"
      PYTHONPATH: '/project'
      SHELL: '/bin/bash'

    volumes:
     - './data:/app/data'
    # - '/path/to/.aiida/repository/myprofile:/app/.aiida/repository/generic'
    ports:
      - '5006:5006'
